### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Cid2mizard** [Annihilator708/Particle-Fire-Explosion#1]
Hello,

I have test with SX OS 1.6, when i launch it, it close my switch...

Cid.

**Comment by 0x78f1935** [comment]
What is the firmware of your switch?

**Comment by 0x78f1935** [comment]
Just tested it with SX OS1.6. Works great. Make sure to get the content of the prebuild folder.
`Particle-Fire-Explosion\Nintendo_Switch\prebuild`. You will find a `.nro` file. Put this one on your sd: `/switch`

**Comment by Cid2mizard** [comment]
Now, it's works but yesterday not, sorry...
